# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sensor_actuator_emulator.xdc

# Block Designs: bd/sensor_actuator_emulator/sensor_actuator_emulator.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator || ORIG_REF_NAME==sensor_actuator_emulator}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_iic_0_0/sensor_actuator_emulator_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_iic_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_iic_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_uartlite_0_0/sensor_actuator_emulator_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconstant_1_0/sensor_actuator_emulator_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconstant_1_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconstant_1_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_i2c_master_multi_slave_con_0_2/sensor_actuator_emulator_i2c_master_multi_slave_con_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_i2c_master_multi_slave_con_0_2 || ORIG_REF_NAME==sensor_actuator_emulator_i2c_master_multi_slave_con_0_2}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconcat_0_0/sensor_actuator_emulator_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconcat_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconcat_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconcat_1_0/sensor_actuator_emulator_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconcat_1_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconcat_1_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconcat_2_0/sensor_actuator_emulator_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconcat_2_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconcat_2_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconcat_3_0/sensor_actuator_emulator_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconcat_3_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconcat_3_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlslice_0_2/sensor_actuator_emulator_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlslice_0_2 || ORIG_REF_NAME==sensor_actuator_emulator_xlslice_0_2}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlslice_1_0/sensor_actuator_emulator_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlslice_1_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlslice_1_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlslice_2_0/sensor_actuator_emulator_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlslice_2_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlslice_2_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlslice_3_0/sensor_actuator_emulator_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlslice_3_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlslice_3_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xadc_wiz_0_0/sensor_actuator_emulator_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xadc_wiz_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_xadc_wiz_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_processing_system7_0_0/sensor_actuator_emulator_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_processing_system7_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_processing_system7_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_processing_system7_0_axi_periph_0/sensor_actuator_emulator_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==sensor_actuator_emulator_processing_system7_0_axi_periph_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_rst_processing_system7_0_100M_0/sensor_actuator_emulator_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_quad_spi_0_0/sensor_actuator_emulator_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_imu_sensor_0_0/sensor_actuator_emulator_imu_sensor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_imu_sensor_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_imu_sensor_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_imu_sensor_1_0/sensor_actuator_emulator_imu_sensor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_imu_sensor_1_0 || ORIG_REF_NAME==sensor_actuator_emulator_imu_sensor_1_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_imu_sensor_2_0/sensor_actuator_emulator_imu_sensor_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_imu_sensor_2_0 || ORIG_REF_NAME==sensor_actuator_emulator_imu_sensor_2_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_timer_0_0/sensor_actuator_emulator_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_timer_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_timer_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xbar_1/sensor_actuator_emulator_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xbar_1 || ORIG_REF_NAME==sensor_actuator_emulator_xbar_1}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_pwm_hall_0_0/sensor_actuator_emulator_pwm_hall_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_pwm_hall_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_pwm_hall_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_util_vector_logic_0_0/sensor_actuator_emulator_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_util_vector_logic_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_util_vector_logic_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_util_vector_logic_2_0/sensor_actuator_emulator_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_util_vector_logic_2_0 || ORIG_REF_NAME==sensor_actuator_emulator_util_vector_logic_2_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_i2c_spi_master_select_0_0/sensor_actuator_emulator_i2c_spi_master_select_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_i2c_spi_master_select_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_i2c_spi_master_select_0_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xlconcat_4_0/sensor_actuator_emulator_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xlconcat_4_0 || ORIG_REF_NAME==sensor_actuator_emulator_xlconcat_4_0}]

# IP: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_auto_pc_0/sensor_actuator_emulator_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_auto_pc_0 || ORIG_REF_NAME==sensor_actuator_emulator_auto_pc_0}]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_iic_0_0/sensor_actuator_emulator_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_iic_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_iic_0_0/sensor_actuator_emulator_axi_iic_0_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_uartlite_0_0/sensor_actuator_emulator_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_uartlite_0_0/sensor_actuator_emulator_axi_uartlite_0_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_uartlite_0_0/sensor_actuator_emulator_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xadc_wiz_0_0/sensor_actuator_emulator_xadc_wiz_0_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xadc_wiz_0_0/sensor_actuator_emulator_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_xadc_wiz_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_processing_system7_0_0/sensor_actuator_emulator_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_processing_system7_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_rst_processing_system7_0_100M_0/sensor_actuator_emulator_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_rst_processing_system7_0_100M_0/sensor_actuator_emulator_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==sensor_actuator_emulator_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_rst_processing_system7_0_100M_0/sensor_actuator_emulator_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_quad_spi_0_0/sensor_actuator_emulator_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_quad_spi_0_0/sensor_actuator_emulator_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_quad_spi_0_0/sensor_actuator_emulator_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_quad_spi_0_0/sensor_actuator_emulator_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_timer_0_0/sensor_actuator_emulator_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sensor_actuator_emulator_axi_timer_0_0 || ORIG_REF_NAME==sensor_actuator_emulator_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_axi_timer_0_0/sensor_actuator_emulator_axi_timer_0_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_xbar_1/sensor_actuator_emulator_xbar_1_ooc.xdc

# XDC: bd/sensor_actuator_emulator/ip/sensor_actuator_emulator_auto_pc_0/sensor_actuator_emulator_auto_pc_0_ooc.xdc

# XDC: bd/sensor_actuator_emulator/sensor_actuator_emulator_ooc.xdc
