webtalk_init -webtalk_dir C:\\Users\\jpnib\\Documents\\TMP\\sensor_actuator_emulator\\sensor_actuator_emulator.sdk\\sdk_workspace\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "So Jän 26 19:33:50 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "h4jnb34q5hgboifvld99qio0ap" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1737911292000" -context "sdk\\\\bsp/1737911292000"
webtalk_add_data -client sdk -key hwid -value "1737500955656" -context "sdk\\\\bsp/1737911292000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1737911292000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_dram_test" -context "sdk\\\\bsp/1737911292000"
webtalk_add_data -client sdk -key uid -value "1737911294858" -context "sdk\\\\application/1737911294858"
webtalk_add_data -client sdk -key hwid -value "1737500955656" -context "sdk\\\\application/1737911294858"
webtalk_add_data -client sdk -key bspid -value "1737911292000" -context "sdk\\\\application/1737911294858"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1737911294858"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1737911294858"
webtalk_add_data -client sdk -key apptemplate -value "zynq_dram_test" -context "sdk\\\\application/1737911294858"
webtalk_transmit -clientid 323881489 -regid "" -xml C:\\Users\\jpnib\\Documents\\TMP\\sensor_actuator_emulator\\sensor_actuator_emulator.sdk\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\jpnib\\Documents\\TMP\\sensor_actuator_emulator\\sensor_actuator_emulator.sdk\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\jpnib\\Documents\\TMP\\sensor_actuator_emulator\\sensor_actuator_emulator.sdk\\sdk_workspace\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
